language: c
script: asdf plugin-test azctx https://github.com/janpieper/asdf-azctx.git --asdf-plugin-gitref=main
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
